project 'FileExplorer.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FileExplorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FileExplorer
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'FileBrowser', '~> 0.2'
  
  target 'FileExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FileExplorerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
